"""@generated by tools/wiregen.py from schema/honba.wire.schema.json - DO NOT EDIT.

Wire schema v1.0.0: the types shared with Rust (``honba_core::wire``) and
TypeScript (``web2/src/core/wire.ts``). See ``docs/data/wire-format.md``.

Serialise with :func:`dumps` (drops unset optionals, emits decimals as strings) and parse
with ``Model.model_validate_json`` (or :data:`MarketEventAdapter` for the union).
"""

# ruff: noqa
from __future__ import annotations

from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter

WIRE_VERSION = "1.0.0"


class _Wire(BaseModel):
    model_config = ConfigDict(extra="ignore")


class AssetClass(StrEnum):
    """What an instrument is. Superset of WonderTrader ContractCategory, QuantDinger market_category and honba MarketSegment."""

    EQUITY = "equity"
    INDEX = "index"
    ETF = "etf"
    MUTUAL_FUND = "mutual_fund"
    BOND = "bond"
    FUTURE = "future"
    OPTION = "option"
    COMMODITY = "commodity"
    CURRENCY = "currency"
    CRYPTO_SPOT = "crypto_spot"
    CRYPTO_SWAP = "crypto_swap"
    CRYPTO_FUTURE = "crypto_future"
    CRYPTO_OPTION = "crypto_option"


class OptionKind(StrEnum):
    CALL = "call"
    PUT = "put"


class Side(StrEnum):
    """Order / fill direction."""

    BUY = "buy"
    SELL = "sell"


class PositionSide(StrEnum):
    """Holding direction."""

    LONG = "long"
    SHORT = "short"


class Offset(StrEnum):
    """Open/close intent for venues that distinguish it (not used on NSE/BSE cash)."""

    OPEN = "open"
    CLOSE = "close"
    CLOSE_TODAY = "close_today"
    CLOSE_YESTERDAY = "close_yesterday"


class OrderType(StrEnum):
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class TimeInForce(StrEnum):
    DAY = "day"
    IOC = "ioc"
    FOK = "fok"
    GTC = "gtc"


class Product(StrEnum):
    """Indian broker product type."""

    CNC = "CNC"
    MIS = "MIS"
    NRML = "NRML"
    MTF = "MTF"


class OrderStatus(StrEnum):
    SUBMITTING = "submitting"
    OPEN = "open"
    PENDING = "pending"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"
    REJECTED = "rejected"


class Timeframe(StrEnum):
    TICK = "tick"
    M1 = "1m"
    M3 = "3m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    D1 = "1d"
    W1 = "1w"
    MO1 = "1M"


class SessionPhase(StrEnum):
    BEFORE_TRADING = "before_trading"
    NOT_TRADING = "not_trading"
    CONTINUOUS = "continuous"
    AUCTION_ORDER = "auction_order"
    AUCTION_BALANCE = "auction_balance"
    AUCTION_MATCH = "auction_match"
    CLOSED = "closed"


class ExecutionMode(StrEnum):
    BACKTEST = "backtest"
    PAPER = "paper"
    LIVE = "live"
    SIGNAL = "signal"


class StrategyStatus(StrEnum):
    STOPPED = "stopped"
    RUNNING = "running"
    PAUSED = "paused"
    ERROR = "error"


class FillReason(StrEnum):
    SIGNAL = "signal"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    SQUARE_OFF = "square_off"
    LIQUIDATE_END = "liquidate_end"


class FeeAlgo(StrEnum):
    NONE = "none"
    PER_QTY = "per_qty"
    PER_VALUE = "per_value"


class FeeSpec(_Wire):
    """Per-instrument fee schedule (exchange/broker level; statutory Indian taxes live in Costs)."""

    algo: FeeAlgo
    open: float | None = None
    close: float | None = None
    close_today: float | None = None


class Instrument(_Wire):
    """Tradable instrument reference data (WTSContractInfo + WTSCommodityInfo + honba Instrument enum)."""

    symbol: str
    code: str
    exchange: str
    asset_class: AssetClass
    name: str | None = None
    isin: str | None = None
    underlying: str | None = None
    product_id: str | None = None
    currency: str | None = None
    lot_size: float
    multiplier: float | None = None
    tick_size: float
    qty_step: float | None = None
    min_qty: float | None = None
    max_market_qty: float | None = None
    max_limit_qty: float | None = None
    freeze_qty: float | None = None
    price_band_pct: float | None = None
    settlement_days: int | None = None
    listed_ms: int | None = None
    expiry_ms: int | None = None
    strike: float | None = None
    option_kind: OptionKind | None = None
    long_margin_rate: float | None = None
    short_margin_rate: float | None = None
    fees: FeeSpec | None = None
    session: str | None = None


class Bar(_Wire):
    """One OHLCV candle. `time_ms` is the bar's open time."""

    symbol: str
    timeframe: Timeframe
    time_ms: int
    open: float
    high: float
    low: float
    close: float
    volume: float
    turnover: float | None = None
    open_interest: float | None = None
    settle: float | None = None


class DepthLevel(_Wire):
    price: float
    qty: float


class Tick(_Wire):
    """Level-1/N snapshot. `volume`/`turnover` are since the previous tick; `total_*` are session cumulative."""

    symbol: str
    time_ms: int
    trading_date: int | None = None
    price: float
    open: float | None = None
    high: float | None = None
    low: float | None = None
    pre_close: float | None = None
    pre_settle: float | None = None
    settle: float | None = None
    upper_limit: float | None = None
    lower_limit: float | None = None
    volume: float | None = None
    total_volume: float | None = None
    turnover: float | None = None
    total_turnover: float | None = None
    open_interest: float | None = None
    pre_open_interest: float | None = None
    bids: list[DepthLevel] | None = None
    asks: list[DepthLevel] | None = None


class TickEvent(_Wire):
    kind: Literal["tick"] = "tick"
    tick: Tick


class BarEvent(_Wire):
    kind: Literal["bar"] = "bar"
    bar: Bar


MarketEvent = Annotated[TickEvent | BarEvent, Field(discriminator="kind")]
"""Streamed market data (tagged by `kind`)."""
MarketEventAdapter: TypeAdapter[TickEvent | BarEvent] = TypeAdapter(MarketEvent)


class Trail(_Wire):
    offset: float
    is_pct: bool


class OrderRequest(_Wire):
    """Intent to trade, as submitted by a strategy or a UI."""

    client_order_id: str
    symbol: str
    side: Side
    order_type: OrderType
    product: Product | None = None
    tif: TimeInForce | None = None
    qty: float
    price: float | None = None
    trigger_price: float | None = None
    offset: Offset | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    trail: Trail | None = None
    strategy_id: str | None = None
    tag: str | None = None
    time_ms: int


class Order(_Wire):
    """An order and its lifecycle state (request + engine/broker state)."""

    order_id: str
    request: OrderRequest
    status: OrderStatus
    filled_qty: float
    avg_fill_price: float | None = None
    reason: str | None = None
    created_ms: int
    updated_ms: int


class Costs(_Wire):
    """Transaction costs of a fill, per component (quote currency). Mirrors honba TradeCosts."""

    brokerage: Decimal | None = None
    stt: Decimal | None = None
    exchange_fee: Decimal | None = None
    sebi_fee: Decimal | None = None
    stamp_duty: Decimal | None = None
    gst: Decimal | None = None
    dp: Decimal | None = None
    total: Decimal


class Fill(_Wire):
    fill_id: str
    order_id: str
    symbol: str
    side: Side
    qty: Decimal
    price: Decimal
    reason: FillReason | None = None
    costs: Costs | None = None
    time_ms: int


class Position(_Wire):
    symbol: str
    product: Product | None = None
    side: PositionSide
    qty: Decimal
    avg_price: Decimal
    mark_price: Decimal | None = None
    realized_pnl: Decimal
    unrealized_pnl: Decimal
    margin: Decimal | None = None
    prev_qty: Decimal | None = None
    available_qty: Decimal | None = None
    updated_ms: int


class Account(_Wire):
    account_id: str
    currency: str
    cash: Decimal
    available: Decimal | None = None
    unsettled: Decimal | None = None
    margin_used: Decimal | None = None
    equity: Decimal
    realized_pnl: Decimal | None = None
    unrealized_pnl: Decimal | None = None
    fees_paid: Decimal | None = None
    time_ms: int


class Signal(_Wire):
    strategy_id: str
    symbol: str
    side: Side
    strength: float | None = None
    target_qty: float | None = None
    reason: str | None = None
    time_ms: int


class StrategyConfig(_Wire):
    strategy_id: str
    name: str
    execution_mode: ExecutionMode
    status: StrategyStatus | None = None
    symbols: list[str]
    timeframe: Timeframe
    initial_capital: Decimal
    leverage: float | None = None
    params: dict[str, Any] | None = None
    created_ms: int | None = None
    updated_ms: int | None = None


class EquityPoint(_Wire):
    time_ms: int
    equity: float


class RoundTrip(_Wire):
    """One completed entry-to-exit trade in a backtest."""

    symbol: str
    side: PositionSide
    qty: float
    entry_ms: int
    exit_ms: int
    entry_price: float
    exit_price: float
    pnl: float
    costs: float | None = None
    exit_reason: FillReason | None = None


class Metrics(_Wire):
    total_return: float
    cagr: float | None = None
    sharpe: float | None = None
    sortino: float | None = None
    max_drawdown: float
    win_rate: float | None = None
    profit_factor: float | None = None
    n_trades: int


class BacktestRun(_Wire):
    run_id: str
    strategy_id: str
    symbols: list[str]
    timeframe: Timeframe
    start_ms: int
    end_ms: int
    initial_capital: Decimal
    params: dict[str, Any] | None = None
    metrics: Metrics
    trades: list[RoundTrip] | None = None
    equity: list[EquityPoint] | None = None
    created_ms: int | None = None


def dumps(obj: BaseModel) -> str:
    """Canonical wire JSON for a model (unset optionals omitted, decimals as strings)."""
    return obj.model_dump_json(exclude_none=True)
