// @generated by tools/wiregen.py from schema/honba.wire.schema.json - DO NOT EDIT.
//
// Wire schema v1.0.0: the types shared with Rust (honba_core::wire) and
// Python (honba.wire). See docs/data/wire-format.md.

export const WIRE_VERSION = "1.0.0";

/** Exact decimal, serialised as a JSON string (parse with a decimal library, not parseFloat). */
export type Decimal = string;

/** What an instrument is. Superset of WonderTrader ContractCategory, QuantDinger market_category and honba MarketSegment. */
export const ASSET_CLASS_VALUES = ["equity", "index", "etf", "mutual_fund", "bond", "future", "option", "commodity", "currency", "crypto_spot", "crypto_swap", "crypto_future", "crypto_option"] as const;
export type AssetClass = (typeof ASSET_CLASS_VALUES)[number];

export const OPTION_KIND_VALUES = ["call", "put"] as const;
export type OptionKind = (typeof OPTION_KIND_VALUES)[number];

/** Order / fill direction. */
export const SIDE_VALUES = ["buy", "sell"] as const;
export type Side = (typeof SIDE_VALUES)[number];

/** Holding direction. */
export const POSITION_SIDE_VALUES = ["long", "short"] as const;
export type PositionSide = (typeof POSITION_SIDE_VALUES)[number];

/** Open/close intent for venues that distinguish it (not used on NSE/BSE cash). */
export const OFFSET_VALUES = ["open", "close", "close_today", "close_yesterday"] as const;
export type Offset = (typeof OFFSET_VALUES)[number];

export const ORDER_TYPE_VALUES = ["market", "limit", "stop", "stop_limit"] as const;
export type OrderType = (typeof ORDER_TYPE_VALUES)[number];

export const TIME_IN_FORCE_VALUES = ["day", "ioc", "fok", "gtc"] as const;
export type TimeInForce = (typeof TIME_IN_FORCE_VALUES)[number];

/** Indian broker product type. */
export const PRODUCT_VALUES = ["CNC", "MIS", "NRML", "MTF"] as const;
export type Product = (typeof PRODUCT_VALUES)[number];

export const ORDER_STATUS_VALUES = ["submitting", "open", "pending", "partially_filled", "filled", "cancelled", "expired", "rejected"] as const;
export type OrderStatus = (typeof ORDER_STATUS_VALUES)[number];

export const TIMEFRAME_VALUES = ["tick", "1m", "3m", "5m", "15m", "30m", "1h", "1d", "1w", "1M"] as const;
export type Timeframe = (typeof TIMEFRAME_VALUES)[number];

export const SESSION_PHASE_VALUES = ["before_trading", "not_trading", "continuous", "auction_order", "auction_balance", "auction_match", "closed"] as const;
export type SessionPhase = (typeof SESSION_PHASE_VALUES)[number];

export const EXECUTION_MODE_VALUES = ["backtest", "paper", "live", "signal"] as const;
export type ExecutionMode = (typeof EXECUTION_MODE_VALUES)[number];

export const STRATEGY_STATUS_VALUES = ["stopped", "running", "paused", "error"] as const;
export type StrategyStatus = (typeof STRATEGY_STATUS_VALUES)[number];

export const FILL_REASON_VALUES = ["signal", "limit", "stop", "stop_loss", "take_profit", "trailing_stop", "square_off", "liquidate_end"] as const;
export type FillReason = (typeof FILL_REASON_VALUES)[number];

export const FEE_ALGO_VALUES = ["none", "per_qty", "per_value"] as const;
export type FeeAlgo = (typeof FEE_ALGO_VALUES)[number];

/** Per-instrument fee schedule (exchange/broker level; statutory Indian taxes live in Costs). */
export interface FeeSpec {
  algo: FeeAlgo;
  open?: number;
  close?: number;
  close_today?: number;
}

/** Tradable instrument reference data (WTSContractInfo + WTSCommodityInfo + honba Instrument enum). */
export interface Instrument {
  /** Canonical id `{CODE}.{VENUE}`, e.g. RELIANCE.NSE, NIFTY24DECFUT.NSE. */
  symbol: string;
  code: string;
  /** NSE, BSE, MCX, ... */
  exchange: string;
  asset_class: AssetClass;
  name?: string;
  isin?: string;
  underlying?: string;
  /** Product family id, e.g. NIFTY. */
  product_id?: string;
  currency?: string;
  /** Minimum order lot (NSE F&O lot). */
  lot_size: number;
  /** Contract value multiplier (WT m_uVolScale). */
  multiplier?: number;
  tick_size: number;
  qty_step?: number;
  min_qty?: number;
  max_market_qty?: number;
  max_limit_qty?: number;
  freeze_qty?: number;
  price_band_pct?: number;
  settlement_days?: number;
  listed_ms?: number;
  expiry_ms?: number;
  strike?: number;
  option_kind?: OptionKind;
  long_margin_rate?: number;
  short_margin_rate?: number;
  fees?: FeeSpec;
  /** Trading-session template id. */
  session?: string;
}

/** One OHLCV candle. `time_ms` is the bar's open time. */
export interface Bar {
  symbol: string;
  timeframe: Timeframe;
  time_ms: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  turnover?: number;
  open_interest?: number;
  settle?: number;
}

export interface DepthLevel {
  price: number;
  qty: number;
}

/** Level-1/N snapshot. `volume`/`turnover` are since the previous tick; `total_*` are session cumulative. */
export interface Tick {
  symbol: string;
  time_ms: number;
  /** YYYYMMDD */
  trading_date?: number;
  price: number;
  open?: number;
  high?: number;
  low?: number;
  pre_close?: number;
  pre_settle?: number;
  settle?: number;
  upper_limit?: number;
  lower_limit?: number;
  volume?: number;
  total_volume?: number;
  turnover?: number;
  total_turnover?: number;
  open_interest?: number;
  pre_open_interest?: number;
  bids?: DepthLevel[];
  asks?: DepthLevel[];
}

export interface TickEvent {
  kind: "tick";
  tick: Tick;
}

export interface BarEvent {
  kind: "bar";
  bar: Bar;
}

/** Streamed market data (tagged by `kind`). */
export type MarketEvent = TickEvent | BarEvent;

export interface Trail {
  offset: number;
  is_pct: boolean;
}

/** Intent to trade, as submitted by a strategy or a UI. */
export interface OrderRequest {
  client_order_id: string;
  symbol: string;
  side: Side;
  order_type: OrderType;
  product?: Product;
  tif?: TimeInForce;
  qty: number;
  price?: number;
  trigger_price?: number;
  offset?: Offset;
  stop_loss?: number;
  take_profit?: number;
  trail?: Trail;
  strategy_id?: string;
  tag?: string;
  time_ms: number;
}

/** An order and its lifecycle state (request + engine/broker state). */
export interface Order {
  order_id: string;
  request: OrderRequest;
  status: OrderStatus;
  filled_qty: number;
  avg_fill_price?: number;
  /** Reject / cancel reason code or message. */
  reason?: string;
  created_ms: number;
  updated_ms: number;
}

/** Transaction costs of a fill, per component (quote currency). Mirrors honba TradeCosts. */
export interface Costs {
  brokerage?: Decimal;
  stt?: Decimal;
  exchange_fee?: Decimal;
  sebi_fee?: Decimal;
  stamp_duty?: Decimal;
  gst?: Decimal;
  dp?: Decimal;
  total: Decimal;
}

export interface Fill {
  fill_id: string;
  order_id: string;
  symbol: string;
  side: Side;
  qty: Decimal;
  price: Decimal;
  reason?: FillReason;
  costs?: Costs;
  time_ms: number;
}

export interface Position {
  symbol: string;
  product?: Product;
  side: PositionSide;
  /** Absolute quantity held. */
  qty: Decimal;
  avg_price: Decimal;
  mark_price?: Decimal;
  realized_pnl: Decimal;
  unrealized_pnl: Decimal;
  margin?: Decimal;
  /** Carried from earlier sessions (WT m_dPrePosition). */
  prev_qty?: Decimal;
  /** Closable now (T+1 / unsettled excluded). */
  available_qty?: Decimal;
  updated_ms: number;
}

export interface Account {
  account_id: string;
  currency: string;
  cash: Decimal;
  available?: Decimal;
  unsettled?: Decimal;
  margin_used?: Decimal;
  equity: Decimal;
  realized_pnl?: Decimal;
  unrealized_pnl?: Decimal;
  fees_paid?: Decimal;
  time_ms: number;
}

export interface Signal {
  strategy_id: string;
  symbol: string;
  side: Side;
  /** 0..1 conviction. */
  strength?: number;
  target_qty?: number;
  reason?: string;
  time_ms: number;
}

export interface StrategyConfig {
  strategy_id: string;
  name: string;
  execution_mode: ExecutionMode;
  status?: StrategyStatus;
  symbols: string[];
  timeframe: Timeframe;
  initial_capital: Decimal;
  leverage?: number;
  /** Free-form strategy parameters. */
  params?: Record<string, unknown>;
  created_ms?: number;
  updated_ms?: number;
}

export interface EquityPoint {
  time_ms: number;
  equity: number;
}

/** One completed entry-to-exit trade in a backtest. */
export interface RoundTrip {
  symbol: string;
  side: PositionSide;
  qty: number;
  entry_ms: number;
  exit_ms: number;
  entry_price: number;
  exit_price: number;
  pnl: number;
  costs?: number;
  exit_reason?: FillReason;
}

export interface Metrics {
  total_return: number;
  cagr?: number;
  sharpe?: number;
  sortino?: number;
  max_drawdown: number;
  win_rate?: number;
  profit_factor?: number;
  n_trades: number;
}

export interface BacktestRun {
  run_id: string;
  strategy_id: string;
  symbols: string[];
  timeframe: Timeframe;
  start_ms: number;
  end_ms: number;
  initial_capital: Decimal;
  params?: Record<string, unknown>;
  metrics: Metrics;
  trades?: RoundTrip[];
  equity?: EquityPoint[];
  created_ms?: number;
}
