//! @generated by tools/wiregen.py from schema/honba.wire.schema.json - DO NOT EDIT.
//!
//! Wire schema v1.0.0: the types shared with Python (`honba.wire`) and
//! TypeScript (`web2/src/core/wire.ts`). See `docs/data/wire-format.md`.

#![allow(clippy::large_enum_variant)]

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub const WIRE_VERSION: &str = "1.0.0";

/// What an instrument is. Superset of WonderTrader ContractCategory, QuantDinger market_category and honba MarketSegment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AssetClass {
    #[serde(rename = "equity")]
    Equity,
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "etf")]
    Etf,
    #[serde(rename = "mutual_fund")]
    MutualFund,
    #[serde(rename = "bond")]
    Bond,
    #[serde(rename = "future")]
    Future,
    #[serde(rename = "option")]
    Option,
    #[serde(rename = "commodity")]
    Commodity,
    #[serde(rename = "currency")]
    Currency,
    #[serde(rename = "crypto_spot")]
    CryptoSpot,
    #[serde(rename = "crypto_swap")]
    CryptoSwap,
    #[serde(rename = "crypto_future")]
    CryptoFuture,
    #[serde(rename = "crypto_option")]
    CryptoOption,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OptionKind {
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "put")]
    Put,
}

/// Order / fill direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Side {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

/// Holding direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PositionSide {
    #[serde(rename = "long")]
    Long,
    #[serde(rename = "short")]
    Short,
}

/// Open/close intent for venues that distinguish it (not used on NSE/BSE cash).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Offset {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "close")]
    Close,
    #[serde(rename = "close_today")]
    CloseToday,
    #[serde(rename = "close_yesterday")]
    CloseYesterday,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderType {
    #[serde(rename = "market")]
    Market,
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "stop_limit")]
    StopLimit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TimeInForce {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "ioc")]
    Ioc,
    #[serde(rename = "fok")]
    Fok,
    #[serde(rename = "gtc")]
    Gtc,
}

/// Indian broker product type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Product {
    #[serde(rename = "CNC")]
    CNC,
    #[serde(rename = "MIS")]
    MIS,
    #[serde(rename = "NRML")]
    NRML,
    #[serde(rename = "MTF")]
    MTF,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "submitting")]
    Submitting,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "partially_filled")]
    PartiallyFilled,
    #[serde(rename = "filled")]
    Filled,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Timeframe {
    #[serde(rename = "tick")]
    Tick,
    #[serde(rename = "1m")]
    M1,
    #[serde(rename = "3m")]
    M3,
    #[serde(rename = "5m")]
    M5,
    #[serde(rename = "15m")]
    M15,
    #[serde(rename = "30m")]
    M30,
    #[serde(rename = "1h")]
    H1,
    #[serde(rename = "1d")]
    D1,
    #[serde(rename = "1w")]
    W1,
    #[serde(rename = "1M")]
    Mo1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SessionPhase {
    #[serde(rename = "before_trading")]
    BeforeTrading,
    #[serde(rename = "not_trading")]
    NotTrading,
    #[serde(rename = "continuous")]
    Continuous,
    #[serde(rename = "auction_order")]
    AuctionOrder,
    #[serde(rename = "auction_balance")]
    AuctionBalance,
    #[serde(rename = "auction_match")]
    AuctionMatch,
    #[serde(rename = "closed")]
    Closed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExecutionMode {
    #[serde(rename = "backtest")]
    Backtest,
    #[serde(rename = "paper")]
    Paper,
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "signal")]
    Signal,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StrategyStatus {
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "error")]
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FillReason {
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "stop_loss")]
    StopLoss,
    #[serde(rename = "take_profit")]
    TakeProfit,
    #[serde(rename = "trailing_stop")]
    TrailingStop,
    #[serde(rename = "square_off")]
    SquareOff,
    #[serde(rename = "liquidate_end")]
    LiquidateEnd,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FeeAlgo {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "per_qty")]
    PerQty,
    #[serde(rename = "per_value")]
    PerValue,
}

/// Per-instrument fee schedule (exchange/broker level; statutory Indian taxes live in Costs).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeeSpec {
    pub algo: FeeAlgo,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub close: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub close_today: Option<f64>,
}

/// Tradable instrument reference data (WTSContractInfo + WTSCommodityInfo + honba Instrument enum).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Instrument {
    /// Canonical id `{CODE}.{VENUE}`, e.g. RELIANCE.NSE, NIFTY24DECFUT.NSE.
    pub symbol: String,
    pub code: String,
    /// NSE, BSE, MCX, ...
    pub exchange: String,
    pub asset_class: AssetClass,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub isin: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub underlying: Option<String>,
    /// Product family id, e.g. NIFTY.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Minimum order lot (NSE F&O lot).
    pub lot_size: f64,
    /// Contract value multiplier (WT m_uVolScale).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multiplier: Option<f64>,
    pub tick_size: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qty_step: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_qty: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_market_qty: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_limit_qty: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub freeze_qty: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price_band_pct: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settlement_days: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub listed_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strike: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub option_kind: Option<OptionKind>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub long_margin_rate: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_margin_rate: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fees: Option<FeeSpec>,
    /// Trading-session template id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
}

/// One OHLCV candle. `time_ms` is the bar's open time.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Bar {
    pub symbol: String,
    pub timeframe: Timeframe,
    pub time_ms: i64,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turnover: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open_interest: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settle: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DepthLevel {
    pub price: f64,
    pub qty: f64,
}

/// Level-1/N snapshot. `volume`/`turnover` are since the previous tick; `total_*` are session cumulative.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tick {
    pub symbol: String,
    pub time_ms: i64,
    /// YYYYMMDD
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trading_date: Option<u32>,
    pub price: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub high: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub low: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_close: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_settle: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settle: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upper_limit: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lower_limit: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_volume: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turnover: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_turnover: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open_interest: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_open_interest: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bids: Option<Vec<DepthLevel>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asks: Option<Vec<DepthLevel>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TickEvent {
    pub tick: Tick,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BarEvent {
    pub bar: Bar,
}

/// Streamed market data (tagged by `kind`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum MarketEvent {
    #[serde(rename = "tick")]
    Tick(TickEvent),
    #[serde(rename = "bar")]
    Bar(BarEvent),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Trail {
    pub offset: f64,
    pub is_pct: bool,
}

/// Intent to trade, as submitted by a strategy or a UI.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OrderRequest {
    pub client_order_id: String,
    pub symbol: String,
    pub side: Side,
    pub order_type: OrderType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product: Option<Product>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tif: Option<TimeInForce>,
    pub qty: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger_price: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<Offset>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_loss: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take_profit: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trail: Option<Trail>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strategy_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    pub time_ms: i64,
}

/// An order and its lifecycle state (request + engine/broker state).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Order {
    pub order_id: String,
    pub request: OrderRequest,
    pub status: OrderStatus,
    pub filled_qty: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avg_fill_price: Option<f64>,
    /// Reject / cancel reason code or message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub created_ms: i64,
    pub updated_ms: i64,
}

/// Transaction costs of a fill, per component (quote currency). Mirrors honba TradeCosts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Costs {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub brokerage: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub stt: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub exchange_fee: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub sebi_fee: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub stamp_duty: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub gst: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub dp: Option<Decimal>,
    #[serde(with = "rust_decimal::serde::str")]
    pub total: Decimal,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Fill {
    pub fill_id: String,
    pub order_id: String,
    pub symbol: String,
    pub side: Side,
    #[serde(with = "rust_decimal::serde::str")]
    pub qty: Decimal,
    #[serde(with = "rust_decimal::serde::str")]
    pub price: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<FillReason>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub costs: Option<Costs>,
    pub time_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Position {
    pub symbol: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product: Option<Product>,
    pub side: PositionSide,
    /// Absolute quantity held.
    #[serde(with = "rust_decimal::serde::str")]
    pub qty: Decimal,
    #[serde(with = "rust_decimal::serde::str")]
    pub avg_price: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub mark_price: Option<Decimal>,
    #[serde(with = "rust_decimal::serde::str")]
    pub realized_pnl: Decimal,
    #[serde(with = "rust_decimal::serde::str")]
    pub unrealized_pnl: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub margin: Option<Decimal>,
    /// Carried from earlier sessions (WT m_dPrePosition).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub prev_qty: Option<Decimal>,
    /// Closable now (T+1 / unsettled excluded).
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub available_qty: Option<Decimal>,
    pub updated_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Account {
    pub account_id: String,
    pub currency: String,
    #[serde(with = "rust_decimal::serde::str")]
    pub cash: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub available: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub unsettled: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub margin_used: Option<Decimal>,
    #[serde(with = "rust_decimal::serde::str")]
    pub equity: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub realized_pnl: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub unrealized_pnl: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        with = "rust_decimal::serde::str_option"
    )]
    pub fees_paid: Option<Decimal>,
    pub time_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Signal {
    pub strategy_id: String,
    pub symbol: String,
    pub side: Side,
    /// 0..1 conviction.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strength: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_qty: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub time_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StrategyConfig {
    pub strategy_id: String,
    pub name: String,
    pub execution_mode: ExecutionMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<StrategyStatus>,
    pub symbols: Vec<String>,
    pub timeframe: Timeframe,
    #[serde(with = "rust_decimal::serde::str")]
    pub initial_capital: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<f64>,
    /// Free-form strategy parameters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<HashMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_ms: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EquityPoint {
    pub time_ms: i64,
    pub equity: f64,
}

/// One completed entry-to-exit trade in a backtest.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RoundTrip {
    pub symbol: String,
    pub side: PositionSide,
    pub qty: f64,
    pub entry_ms: i64,
    pub exit_ms: i64,
    pub entry_price: f64,
    pub exit_price: f64,
    pub pnl: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub costs: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_reason: Option<FillReason>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Metrics {
    pub total_return: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cagr: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sharpe: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sortino: Option<f64>,
    pub max_drawdown: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub win_rate: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_factor: Option<f64>,
    pub n_trades: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BacktestRun {
    pub run_id: String,
    pub strategy_id: String,
    pub symbols: Vec<String>,
    pub timeframe: Timeframe,
    pub start_ms: i64,
    pub end_ms: i64,
    #[serde(with = "rust_decimal::serde::str")]
    pub initial_capital: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<HashMap<String, serde_json::Value>>,
    pub metrics: Metrics,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trades: Option<Vec<RoundTrip>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub equity: Option<Vec<EquityPoint>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_ms: Option<i64>,
}
