#!/usr/bin/env python3
"""Generate Rust, Python and TypeScript bindings from schema/honba.wire.schema.json.

    python tools/wiregen.py           # (re)write the generated files
    python tools/wiregen.py --check   # exit 1 if a generated file is stale (for CI)

Stdlib only. Supports the JSON Schema subset the wire schema uses: string enums, objects with
required/optional properties, ``$ref``, arrays, ``additionalProperties`` maps, ``const`` tags,
``oneOf`` + ``discriminator`` unions, and ``format: decimal | int64 | uint32``.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "honba.wire.schema.json"
OUT_RUST = ROOT / "crates" / "honba-core" / "src" / "wire.rs"
OUT_PY = ROOT / "python" / "honba" / "wire.py"
OUT_TS = ROOT / "web2" / "src" / "core" / "wire.ts"

BANNER = "@generated by tools/wiregen.py from schema/honba.wire.schema.json - DO NOT EDIT."


def pascal(value: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^0-9A-Za-z]+", value) if p)


def upper_snake(value: str) -> str:
    return re.sub(r"[^0-9A-Za-z]+", "_", value).upper()


def snake_const(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def ref_name(node: dict) -> str:
    return node["$ref"].rsplit("/", 1)[-1]


def kind_of(d: dict) -> str:
    if "enum" in d:
        return "enum"
    if "oneOf" in d:
        return "union"
    if d.get("type") == "object" and "properties" in d:
        return "object"
    raise ValueError(f"unsupported definition: {d}")


def enum_names(d: dict) -> list[str]:
    return d.get("x-names") or [pascal(v) for v in d["enum"]]


def doc_lines(d: dict) -> list[str]:
    return [d["description"]] if d.get("description") else []


def toposort(defs: dict) -> list[str]:
    order: list[str] = []
    seen: set[str] = set()

    def deps(node) -> list[str]:
        if isinstance(node, dict):
            if "$ref" in node:
                return [ref_name(node)]
            return [n for v in node.values() for n in deps(v)]
        if isinstance(node, list):
            return [n for v in node for n in deps(v)]
        return []

    def visit(name: str) -> None:
        if name in seen:
            return
        seen.add(name)
        for dep in deps(defs[name]):
            visit(dep)
        order.append(name)

    for name in defs:
        visit(name)
    return order


def const_prop(d: dict) -> tuple[str, str] | None:
    """(property, value) of a union variant's ``const`` discriminator, if any."""
    for prop, spec in d.get("properties", {}).items():
        if "const" in spec:
            return prop, spec["const"]
    return None


# --------------------------------------------------------------------------- Rust


def rust_type(spec: dict) -> str:
    if "$ref" in spec:
        return ref_name(spec)
    t = spec.get("type")
    if t == "string":
        return "Decimal" if spec.get("format") == "decimal" else "String"
    if t == "number":
        return "f64"
    if t == "integer":
        return {"uint32": "u32", "int32": "i32"}.get(spec.get("format"), "i64")
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"Vec<{rust_type(spec['items'])}>"
    if t == "object":
        return "HashMap<String, serde_json::Value>"
    raise ValueError(spec)


def gen_rust(schema: dict) -> str:
    defs = schema["$defs"]
    out = [
        f"//! {BANNER}",
        "//!",
        f"//! Wire schema v{schema['x-version']}: the types shared with Python (`honba.wire`) and",
        "//! TypeScript (`web2/src/core/wire.ts`). See `docs/data/wire-format.md`.",
        "",
        "#![allow(clippy::large_enum_variant)]",
        "",
        "use rust_decimal::Decimal;",
        "use serde::{Deserialize, Serialize};",
        "use std::collections::HashMap;",
        "",
        f'pub const WIRE_VERSION: &str = "{schema["x-version"]}";',
    ]
    for name in toposort(defs):
        d = defs[name]
        out.append("")
        out += [f"/// {line}" for line in doc_lines(d)]
        kind = kind_of(d)
        if kind == "enum":
            out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]")
            out.append(f"pub enum {name} {{")
            for value, ident in zip(d["enum"], enum_names(d)):
                out.append(f'    #[serde(rename = "{value}")]')
                out.append(f"    {ident},")
            out.append("}")
        elif kind == "union":
            tag = d["discriminator"]["propertyName"]
            out.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
            out.append(f'#[serde(tag = "{tag}")]')
            out.append(f"pub enum {name} {{")
            for variant in d["oneOf"]:
                vname = ref_name(variant)
                _, value = const_prop(defs[vname])
                out.append(f'    #[serde(rename = "{value}")]')
                out.append(f"    {pascal(value)}({vname}),")
            out.append("}")
        else:
            out.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
            out.append(f"pub struct {name} {{")
            required = set(d.get("required", []))
            for prop, spec in d["properties"].items():
                if "const" in spec:
                    continue  # carried by the enclosing tagged union
                ty = rust_type(spec)
                decimal = spec.get("format") == "decimal"
                if prop in required:
                    if "description" in spec:
                        out.append(f"    /// {spec['description']}")
                    if decimal:
                        out.append('    #[serde(with = "rust_decimal::serde::str")]')
                    out.append(f"    pub {prop}: {ty},")
                else:
                    if "description" in spec:
                        out.append(f"    /// {spec['description']}")
                    attrs = 'default, skip_serializing_if = "Option::is_none"'
                    if decimal:
                        attrs += ', with = "rust_decimal::serde::str_option"'
                    out.append(f"    #[serde({attrs})]")
                    out.append(f"    pub {prop}: Option<{ty}>,")
            out.append("}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- Python


def py_type(spec: dict) -> str:
    if "$ref" in spec:
        return ref_name(spec)
    t = spec.get("type")
    if t == "string":
        return "Decimal" if spec.get("format") == "decimal" else "str"
    if t == "number":
        return "float"
    if t == "integer":
        return "int"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"list[{py_type(spec['items'])}]"
    if t == "object":
        return "dict[str, Any]"
    raise ValueError(spec)


def gen_python(schema: dict) -> str:
    defs = schema["$defs"]
    out = [
        f'"""{BANNER}',
        "",
        f"Wire schema v{schema['x-version']}: the types shared with Rust (``honba_core::wire``) and",
        "TypeScript (``web2/src/core/wire.ts``). See ``docs/data/wire-format.md``.",
        "",
        "Serialise with :func:`dumps` (drops unset optionals, emits decimals as strings) and parse",
        "with ``Model.model_validate_json`` (or :data:`MarketEventAdapter` for the union).",
        '"""',
        "",
        "# ruff: noqa",
        "from __future__ import annotations",
        "",
        "from decimal import Decimal",
        "from enum import StrEnum",
        "from typing import Annotated, Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field, TypeAdapter",
        "",
        f'WIRE_VERSION = "{schema["x-version"]}"',
        "",
        "",
        "class _Wire(BaseModel):",
        '    model_config = ConfigDict(extra="ignore")',
    ]
    unions: list[str] = []
    for name in toposort(defs):
        d = defs[name]
        kind = kind_of(d)
        if kind == "union":
            tag = d["discriminator"]["propertyName"]
            members = " | ".join(ref_name(v) for v in d["oneOf"])
            out += ["", "", f'{name} = Annotated[{members}, Field(discriminator="{tag}")]']
            if doc_lines(d):
                out.append(f'"""{doc_lines(d)[0]}"""')
            out.append(f"{name}Adapter: TypeAdapter[{members}] = TypeAdapter({name})")
            unions.append(name)
            continue
        out += ["", ""]
        if kind == "enum":
            out.append(f"class {name}(StrEnum):")
            if doc_lines(d):
                out.append(f'    """{doc_lines(d)[0]}"""')
                out.append("")
            for value, ident in zip(d["enum"], d.get("x-names") or d["enum"]):
                out.append(f'    {upper_snake(ident)} = "{value}"')
        else:
            out.append(f"class {name}(_Wire):")
            if doc_lines(d):
                out.append(f'    """{doc_lines(d)[0]}"""')
                out.append("")
            required = set(d.get("required", []))
            for prop, spec in d["properties"].items():
                if "const" in spec:
                    out.append(f'    {prop}: Literal["{spec["const"]}"] = "{spec["const"]}"')
                elif prop in required:
                    out.append(f"    {prop}: {py_type(spec)}")
                else:
                    out.append(f"    {prop}: {py_type(spec)} | None = None")
    out += [
        "",
        "",
        "def dumps(obj: BaseModel) -> str:",
        '    """Canonical wire JSON for a model (unset optionals omitted, decimals as strings)."""',
        "    return obj.model_dump_json(exclude_none=True)",
    ]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- TypeScript


def ts_type(spec: dict) -> str:
    if "$ref" in spec:
        return ref_name(spec)
    t = spec.get("type")
    if t == "string":
        return "Decimal" if spec.get("format") == "decimal" else "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        inner = ts_type(spec["items"])
        return f"{inner}[]"
    if t == "object":
        return "Record<string, unknown>"
    raise ValueError(spec)


def gen_ts(schema: dict) -> str:
    defs = schema["$defs"]
    out = [
        f"// {BANNER}",
        "//",
        f"// Wire schema v{schema['x-version']}: the types shared with Rust (honba_core::wire) and",
        "// Python (honba.wire). See docs/data/wire-format.md.",
        "",
        f'export const WIRE_VERSION = "{schema["x-version"]}";',
        "",
        "/** Exact decimal, serialised as a JSON string (parse with a decimal library, not parseFloat). */",
        "export type Decimal = string;",
    ]
    for name in toposort(defs):
        d = defs[name]
        kind = kind_of(d)
        out.append("")
        if doc_lines(d):
            out.append(f"/** {doc_lines(d)[0]} */")
        if kind == "enum":
            const = snake_const(name) + "_VALUES"
            values = ", ".join(json.dumps(v) for v in d["enum"])
            out.append(f"export const {const} = [{values}] as const;")
            out.append(f"export type {name} = (typeof {const})[number];")
        elif kind == "union":
            members = " | ".join(ref_name(v) for v in d["oneOf"])
            out.append(f"export type {name} = {members};")
        else:
            out.append(f"export interface {name} {{")
            required = set(d.get("required", []))
            for prop, spec in d["properties"].items():
                if "description" in spec:
                    out.append(f"  /** {spec['description']} */")
                if "const" in spec:
                    out.append(f"  {prop}: {json.dumps(spec['const'])};")
                else:
                    opt = "" if prop in required else "?"
                    out.append(f"  {prop}{opt}: {ts_type(spec)};")
            out.append("}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- main


def _pipe(cmd: list[str], text: str) -> str:
    """Run a formatter over ``text``; fall back to the raw text if the tool is unavailable."""
    try:
        done = subprocess.run(cmd, input=text, capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return text
    return done.stdout


def main() -> int:
    schema = json.loads(SCHEMA.read_text())
    outputs = {
        OUT_RUST: _pipe(["rustfmt", "--edition", "2021", "--emit", "stdout"], gen_rust(schema)),
        OUT_PY: _pipe(["ruff", "format", "--stdin-filename", "wire.py", "-"], gen_python(schema)),
        OUT_TS: gen_ts(schema),
    }
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs.items():
        rel = path.relative_to(ROOT)
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(rel))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")
    if stale:
        print("stale generated files (run `python tools/wiregen.py`):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
