[package]
name = "honba-overfit"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
honba-core = { workspace = true }
